######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 14 10:11:15 2010
######################################################################

TEMPLATE = app
TARGET = a.out
QT += xml

DEPENDPATH += . \
        $$PWD/../../code/inc/ \
        $$PWD/../../code/cpp/ \

INCLUDEPATH += . \
        $$PWD/../../code/inc/ \

include($$PWD/../../../graph_lib/code/graph_lib.pri)
include($$PWD/../../code/chart.pri)

HEADERS += \
        window.h \

SOURCES += main.cpp \
        window.cpp \

