######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 14 10:11:15 2010
######################################################################

TEMPLATE = app
TARGET = a.out
QT += xml

DEPENDPATH += . \
        $$PWD/../../code/inc/ \
        $$PWD/../../code/cpp/ \

INCLUDEPATH += . \
        $$PWD/../../code/inc/ \

#GRAPH_LIB_PATH = $$PWD/../../../../../deployment/libs/graph_lib/unix/
#unix:LIBS += -L$${GRAPH_LIB_PATH} -lgraph_lib

#include($$PWD/../../code/graph_tile.pri)
include($$PWD/../../code/graph_lib.pri)

HEADERS += \
        window.h \
        drawable.h \
        #tile.h \
        #tile_manager.h \
        #tile_types.h \

# Input
SOURCES += main.cpp \
        window.cpp \
        drawable.cpp \
        #tile.cpp \
        #tile_manager.cpp \

